platform :ios, ‘9.0’
use_frameworks!

target 'TodoApp' do
	pod 'Alamofire', '~> 4.0'
	pod 'Argo'
    pod 'Curry'
	pod 'ReactiveCocoa', '~> 5.0.0'
	pod 'Delta', :git => "https://github.com/conqueror/Delta.git"
end

target 'TodoAppTests' do

end

