platform :ios, '8.0'
use_frameworks!

target 'TodoApp' do
	pod 'Alamofire'
	pod 'Argo'
    pod 'Curry'
	pod 'ReactiveCocoa'
	pod 'Delta', :git => "https://github.com/thoughtbot/Delta.git"
end

target 'TodoAppTests' do

end

